version: '3.9'
name: 'rinha-brunoborges'

services:
  api1:
    image: rinha-java21-springboot-ccs1201:0.0.1
    hostname: api1
    depends_on:
      - db-postgresql
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: '0.95GB'
    networks:
      - app-network

  api2:
    image: rinha-java21-springboot-ccs1201:0.0.1
    hostname: api2
    depends_on:
      - db-postgresql
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: '0.95GB'
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '100MB'

  db-postgresql:
    image: postgres:latest
    command: 'postgres -c max_connections=200 -c shared_buffers=512MB -c wal_buffers=64MB -c synchronous_commit=off -c fsync=off -c full_page_writes=off'
    hostname: db-postgresql
    environment:
      - POSTGRES_DB=rinha
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1.5GB'
    networks:
      - app-network

networks:
  app-network:
