version: '3'
services:
  postgres:
    image: 'postgres:latest'
    shm_size: 1g
    hostname: postgres
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: '1GB'
    environment:
      - POSTGRES_DB=rinha
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    command: 'postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf'
    #    network_mode: bridge
    ports:
      - '5432:5432'
#    networks:
#      - app_network

  api1: # API - Instância 01
    image: rinha-java21-ccs1201:0.0.1
    hostname: api1
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: '900MB'
    #    network_mode: bridge
    ports:
      - '8081:8080'
#    networks:
#      - app_network

  api2: # API - Instância 02
    image: rinha-java21-ccs1201:0.0.1
    hostname: api2
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: '900MB'
    #    network_mode: bridge
    ports:
      - '8082:8080'
#    networks:
#    - app_network


  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    #    network_mode: host
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.2GB'
    ports:
      - '9999:9999'
#    networks:
#      - app_network


#networks:
#  app_network:
#    driver: bridge