version: '3.9'
name: 'rinha-csouza-java21'

services:
  api1: # API - Instância 01
    image: ccs1201/rinha_tvbox
    hostname: api1
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: "0.325"
          memory: '768MB'
    environment:
      - SERVER_PORT=8081  # Defina a porta desejada para api1
    network_mode: host

  api2: # API - Instância 02
    image: ccs1201/rinha_tvbox
    hostname: api2
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: "0.325"
          memory: '768MB'
    environment:
      - SERVER_PORT=8082  # Defina a porta desejada para api2
    network_mode: host

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    network_mode: host
    depends_on:
      - postgres
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '200MB'

  #Data Base
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=rinha
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    network_mode: host
    volumes:
      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    command: 'postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf'
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1GB'