version: '3'
services:
  api1: # API - Instância 01
    image: ccs1201/rinha_tvbox
    hostname: api1
    deploy:
      resources:
        limits:
          memory: '1500MB'
    #    network_mode: host
    environment:
      - PORTA=8081  # Defina a porta desejada para api1
    networks:
      - app_network

  api2: # API - Instância 02
    image: ccs1201/rinha_tvbox
    hostname: api2
    deploy:
      resources:
        limits:
          memory: '1500MB'
    #    network_mode: host
    environment:
      - PORTA=8082  # Defina a porta desejada para api1
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
#    network_mode: host
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '300MB'
    ports:
      - '9999:9999'
    networks:
      - app_network

networks:
  app_network:
    driver: bridge