version: '3'
services:
  api1: # API - Instância 01
    image: ccs1201/rinha_tvbox
    hostname: api1
    deploy:
      resources:
        limits:
          memory: '1.5GB'
    #    network_mode: host
    networks:
      - app_network

  api2: # API - Instância 02
    image: ccs1201/rinha_tvbox
    hostname: api2
    deploy:
      resources:
        limits:
          memory: '1.5GB'
    #    network_mode: host
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    #    network_mode: host
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '300MB'
    ports:
      - '9999:9999'
    networks:
      - app_network

networks:
  app_network:
    driver: macvlan
    driver_opts:
    	parent: eth0
    ipam:
    	config:
    		- subnet: 192.168.1.0/24
