version: '3'
services:
  api1: # API - Instância 01
    image: rinha-java21-ccs1201:0.0.1
    hostname: api1
    deploy:
      resources:
        limits:
          memory: '1GB'
#    network_mode: host
    ports:
      - '8080:8080'
  #    networks:
  #      - app_network

  api2: # API - Instância 02
    image: rinha-java21-ccs1201:0.0.1
    hostname: api2
    deploy:
      resources:
        limits:
          memory: '1GB'
#    network_mode: host
    ports:
      - '8080:8080'
  #    networks:
  #    - app_network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    #    network_mode: host
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '200MB'
    ports:
      - '9999:9999'
#    networks:
#      - app_network

#networks:
#  app_network:
#    driver: bridge